set -l liquibase_commands init update update-sql update-count update-count-sql update-one-changeset update-one-changeset-sql update-testing-rollback update-to-tag update-to-tag-sql rollback rollback-sql rollback-to-date rollback-to-date-sql rollback-count rollback-count-sql \
rollback-one-changeset rollback-one-changeset-sql rollback-one-update rollback-one-update-sql future-rollback-sql future-rollback-count-sql future-rollback-from-tag-sql generate-changelog snapshot snapshot-reference diff diff-changelog \
history status calculate-checksum changelog-sync changelog-sync-sql changelog-sync-to-tag clear-checksums drop-all execute-sql list-locks mark-next-changeset-ran mark-next-changeset-ran-sql release-locks tag tag-exists unexpected-changesets validate \
db-doc register-changelog sync-hub deactivate-changelog checks --version

set -l liquibase_init_commands hub project start-h2

set -l liquibase_checks_commands run delete bulk-set show customize reset enable disable copy

# Liquibase start commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a init -d 'Select hub, project or start-h2'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and not __fish_seen_subcommand_from $liquibase_init_commands; and not __fish_seen_subcommand_from hub" -a hub -d 'The hub subcommand connects your local Liquibase activity to Liquibase Hub with an API key and sets up the Liquibase environment to use Liquibase Hub'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and not __fish_seen_subcommand_from $liquibase_init_commands; and not __fish_seen_subcommand_from project" -a project -d 'The project subcommand finds or creates your project folder with the changelog and Liquibase properties files and delivers an example H2 database to help you get started'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and not __fish_seen_subcommand_from $liquibase_init_commands; and not __fish_seen_subcommand_from start-h2" -a start-h2 -d 'The start-h2 subcommand starts the in-memory H2 database included in the Liquibase installation package to get started and test how Liquibase works'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --project-dir" -a --project-dir -d 'Relative or fully qualified path to the directory where the project files will be created'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'Relative or fully qualified path to the changelog file'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --format" -a --format -d 'Format of the project changelog file <.sql, .xml, .json, .yaml, .yml>'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --project-defaults-file" -a --project-defaults-file -d 'File with Liquibase properties'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --url" -a --url -d 'Database connection URL (JDBC). For more information, see Using JDBC URL in Liquibase'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --username" -a --username -d 'Username to use to connect to the database'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --password" -a --password -d 'Password to use to connect to the database'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from --guide" -a --guide -d 'Parameter that turns on or turns off the CLI interactive mode. For example, if you want to set one parameter and have the rest as default ones, run the parameter and set --guide=off to not be asked about the rest of the settings: liquibase init project --changelog=mychangelog.sql --guide=off'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from hub; and not __fish_seen_subcommand_from --token" -a --token -d 'The code required to connect local Liquibase activity with Liquibase Hub'
complete -f -c liquibase -n "__fish_seen_subcommand_from init; and __fish_seen_subcommand_from hub; and not __fish_seen_subcommand_from --project-dir" -a --project-dir -d 'The relative or fully qualified path to the directory where the project files are or will be created'

# Database update commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update -d 'Updates database to current version'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-sql -d 'A helper command that allows you to inspect the SQL Liquibase will run while using the update command'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-count -d 'Applies the next <value> changesets'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-count-sql -d 'Writes SQL to apply the next <value> changesets to STDOUT'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-one-changeset -d '**PRO** Targets and deploys any single changeset'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-one-changeset-sql -d '**PRO** Writes SQL to target and deploy any single changeset'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-testing-rollback -d 'Updates the database, then rolls back changes before updating again'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-to-tag -d 'Applies sequential changes to your database from the newest changeset to the changeset with the tag you specified and applied earlier'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a update-to-tag-sql -d 'A helper command that inspects the SQL Liquibase will run while using the update-to-tag <tag> command'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --liquibaseSchemaName" -a --liquibaseSchemaName -d 'Specifies in what schema the LiquibaseDATABASECHANGELOG and DATABASECHANGELOGLOCK tables will be managed'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --liquibaseCatalogName" -a --liquibaseCatalogName -d 'For MSSQL only: Specifies in what catalog the LiquibaseDATABASECHANGELOG and DATABASECHANGELOGLOCK tables will be managed'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --labels" -a --labels -d 'Tags you can add to changesets to determine which changesets in the changelog to evaluate based on their labels'
complete -f -c liquibase -n "__fish_seen_subcommand_from update; and not __fish_seen_subcommand_from --contexts" -a --contexts -d 'Expressions you can add to changesets to determine which changesets in the changelog to evaluate based on their contexts'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --labels" -a --labels -d 'Tags you can add to changesets to determine which changesets in the changelog to evaluate based on their labels'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-sql; and not __fish_seen_subcommand_from --contexts" -a --contexts -d 'Expressions you can add to changesets to determine which changesets in the changelog to evaluate based on their contexts'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-count-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --changeset-id" -a --changeset-id -d 'The changeset ID from the changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --changeset-author" -a --changeset-author -d 'The name of the author for the changeset'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --changeset-path" -a --changeset-path -d 'The path to the changelog containing the changeset you want to roll back'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset; and not __fish_seen_subcommand_from --force" -a --force -d 'A required parameter which indicates you intend to use this feature'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --changeset-id" -a --changeset-id -d 'The changeset ID from the changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --changeset-author" -a --changeset-author -d 'The name of the author for the changeset'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-one-changeset-sql; and not __fish_seen_subcommand_from --changeset-path" -a --changeset-path -d 'The path to the changelog containing the changeset you want to roll back'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-testing-rollback; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-testing-rollback; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-testing-rollback; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-testing-rollback; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from update-to-tag-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'

# Database rollback commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback -d 'Rolls back the database to the state it was in when the tag was applied'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-sql -d 'A helper command that produces the raw SQL Liquibase would run when using the rollbackByTag command'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-to-date -d 'Rolls back the database to the state it was in at the given date/time'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-to-date-sql -d 'A helper command that allows you to inspect the SQL Liquibase will run while using the rollback-to-date command'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-count -d 'Rolls back the last <value> changesets'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-count-sql -d 'Writes SQL to roll back the last <value> changesets to STDOUT'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-one-changeset -d '**PRO** Rolls back a single changeset without needing to roll back other already applied changeset'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-one-changeset-sql -d '**PRO** Writes SQL to roll back a single changeset to STDOUT'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-one-update -d '**PRO** Rolls back all changesets related by a specific deploymentId that was made during a previous change to your database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a rollback-one-update-sql -d '**PRO** A helper command that allows you to inspect the SQL Liquibase will run to revert all changeset associated with the deploymentID specified in the rollback-one-update command'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a future-rollback-sql -d 'Writes SQL to roll back the database to the current state after the changes in the changelog have been applied'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a future-rollback-count-sql -d 'Generates the SQL that Liquibase would use to sequentially revert the number of changes associated with undeployed changesets, which are added to a changelog file'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a future-rollback-from-tag-sql -d 'Produces the raw SQL Liquibase would need to roll back all undeployed changes made up to the specified tag'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-to-date-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-count-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --changeset-id" -a --changeset-id -d 'The changeset ID from the changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --changeset-author" -a --changeset-author -d 'The name of the author for the changeset'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --changeset-path" -a --changeset-path -d 'The path to the changelog containing the changeset you want to roll back'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --force" -a --force -d 'A required parameter which indicates you intend to use this feature'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset; and not __fish_seen_subcommand_from --rollback-script" -a --rollback-script -d 'The path to the script to use to perform the rollback'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --changeset-id" -a --changeset-id -d 'The changeset ID from the changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --changeset-author" -a --changeset-author -d 'The name of the author for the changeset'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --changeset-path" -a --changeset-path -d 'The path to the changelog containing the changeset you want to roll back'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-changeset-sql; and not __fish_seen_subcommand_from --rollback-script" -a --rollback-script -d 'The path to the script to use to perform the rollback'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --deploymentId" -a --deploymentId -d 'Specifies the deploymentId of all from the DATABASECHANGELOG table related to the changesets intended for rollback'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update; and not __fish_seen_subcommand_from --force" -a --force -d 'A required parameter which indicates you intend to use this feature'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from rollback-one-update-sql; and not __fish_seen_subcommand_from --deploymentId" -a --deploymentId -d 'Specifies the deploymentId of all from the DATABASECHANGELOG table related to the changesets intended for rollback'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-count-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-count-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-count-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-count-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-count-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-from-tag-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-from-tag-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-from-tag-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-from-tag-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from future-rollback-from-tag-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'

# Database snapshot commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a generate-changelog -d 'Generate a changelog from a database when adding Liquibase to a new project. This is synonymous with snapshot with the exception of saving the output as XML in the changelog'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a snapshot -d 'Gathers the current database schema and displays that information to STDOUT. With options, can save the schema in JSON format, and that JSON snapshot can serve as a comparison database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a snapshot-reference -d 'Captures the current state of the referenceURL database, which is the source database'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --defaultCatalogName" -a --defaultCatalogName -d 'Specifies the default database catalog to use'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --defaultSchemaName" -a --defaultSchemaName -d 'Specifies the default database schema to use'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --driver" -a --driver -d 'The JDBC driver class'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --driverPropertiesFile" -a --driverPropertiesFile -d 'The JDBC driver properties file'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --excludeObjects" -a --excludeObjects -d 'Objects to exclude from diff'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --includeObjects" -a --includeObjects -d 'Objects to include in diff'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --dataOutputDirectory" -a --dataOutputDirectory -d 'Sends the data output as a CSV file in the given directory'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --diffTypes" -a --diffTypes -d 'Includes a list of diff types in a changelog file expressed as a comma-separated list (without spaces) from: catalogs,tables,functions,views,columns,indexes,foreignkeys,primarykeys,uniqueconstraints,data,storedprocedures,triggers,sequences,databasepackage,databasepackagebody.'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --includeCatalog" -a --includeCatalog -d 'Includes the catalog in a generated changesets if the value is true. The default value is false'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --includeSchema" -a --includeSchema -d 'Includes the schema in a generated changesets if the value is true. The default value is false'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --includeTablespace" -a --includeTablespace -d 'Includes the tablespace of tables and indexes in a generated changesets if the value is true. The default value is false'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --outputSchemaAs" -a --outputSchemaAs -d 'Uses the names as schemaName instead of the real names on the generate-changelog command'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --overwriteOutputFile" -a --overwriteOutputFile -d 'Determines whether generate-changelog can overwrite an existing changelog, including one specified in --changelog-file. The default value is false'
complete -f -c liquibase -n "__fish_seen_subcommand_from generate-changelog; and not __fish_seen_subcommand_from --schemas" -a --schemas -d 'Specifies database schemas you want to include'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --schemas" -a --schemas -d 'Specifies database schemas you want to include'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot; and not __fish_seen_subcommand_from --snapshotFormat" -a --snapshotFormat -d 'Creates a JSON or YAML file that represents the current state of the database'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot-reference; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot-reference; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot-reference; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from snapshot-reference; and not __fish_seen_subcommand_from --snapshotFormat" -a --snapshotFormat -d 'Creates a JSON or YAML file that represents the current state of the database'

# Database diff commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a diff -d 'Writes description of differences between two databases to standard out'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a diff-changelog -d 'Adds any differences between the databases specified to a changelog. Can append in any of the supported changelog formats'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --referenceUrl" -a --referenceUrl -d 'Base Database URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --referenceUsername" -a --referenceUsername -d 'Base Database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --referencePassword" -a --referencePassword -d 'Base Database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --format=json" -a --format=json -d 'Starting with Liquibase 3.9.0, you can automate drift detection at scale in your database schemas with the Liquibase Pro machine-readable JSON diff output. The diff --format=json command is a Liquibase Pro extension to the Liquibase Community diff command'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff; and not __fish_seen_subcommand_from --liquibaseProLicenseKey" -a --liquibaseProLicenseKey -d 'Your Liquibase Pro license key'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --referenceUrl" -a --referenceUrl -d 'Base Database URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --referenceUsername" -a --referenceUsername -d 'Base Database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --referencePassword" -a --referencePassword -d 'Base Database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --diffTypes" -a --diffTypes -d 'You can filter what objects diff-changelog generates with the diffTypes attribute. <catalogs,tables,functions,views,columns,indexes,foreignkeys,primarykeys,uniqueconstraints,storedprocedures,triggers,sequences,databasepackage,databasepackagebody>'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --includeObjects" -a --includeObjects -d 'Objects to include from diff'
complete -f -c liquibase -n "__fish_seen_subcommand_from diff-changelog; and not __fish_seen_subcommand_from --excludeObjects" -a --excludeObjects -d 'Objects to exclude from diff'

# Status commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a history -d 'Lists all deployed changesets and their deploymentIds'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a status -d 'Outputs the count (or list, if --verbose) of changesets that have not been deployed'
complete -f -c liquibase -n "__fish_seen_subcommand_from history; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from history; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from history; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from history; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from status; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from status; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from status; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from status; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from status; and not __fish_seen_subcommand_from --verbose" -a --verbose -d 'Specify the detail level of the output'

# Maintenance commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a calculate-checksum -d 'Calculates and prints a checksum for the changeset with the specified id in the following format: filepath::id::author'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a changelog-sync -d 'Marks all changes as executed in the database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a changelog-sync-sql -d 'Writes SQL to mark all changes as executed in the database to STDOUT'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a changelog-sync-to-tag -d 'Marks all undeployed changesets from your changelog up to and including the specified tag as executed in your database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a changelog-sync-to-tag-sql -d 'Produces the raw SQL that Liquibase would run when using the changelog-sync-to-tag command to mark all undeployed changesets associated with the specified tag as executed in your database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a clear-checksums -d 'Removes current checksums from database. On next update changesets that have already been deployed will have their checksums recomputed, and changesets that have not been deployed will be deployed'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a drop-all -d 'Drops all database objects owned by the user'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a execute-sql -d 'Executes a SQL string or file'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a list-locks -d 'Lists who currently has locks on the database changelog'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a mark-next-changeset-ran -d 'Mark the next change set as executed in the database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a mark-next-changeset-ran-sql -d 'Mark the next change set as executed in the database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a release-locks -d 'Mark the next change set as executed in the database'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a tag -d '"Tags" the current database state for future rollback'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a tag-exists -d 'Checks whether the given tag already exists'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a unexpected-changesets -d 'Produces a list of changesets that were run in the database but do not exist in the current changelog'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a validate -d 'Checks the changelog for errors'
complete -f -c liquibase -n "__fish_seen_subcommand_from calculate-checksum; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from calculate-checksum; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from calculate-checksum; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from calculate-checksum; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from changelog-sync-to-tag-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from clear-checksum; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from clear-checksum; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from clear-checksum; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from drop-all; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from drop-all; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from drop-all; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from drop-all; and not __fish_seen_subcommand_from --hubConnectionId" -a --hubConnectionId -d 'Identifies the specific target in which to record your data at Liquibase Hub. The attribute is available in your Project at https://hub.liquibase.com'
complete -f -c liquibase -n "__fish_seen_subcommand_from drop-all; and not __fish_seen_subcommand_from --hubProjectId" -a --hubProjectId -d 'Identifies the specific Project in which to record your data at Liquibase Hub. The attribute is available in your account at https://hub.liquibase.com'
complete -f -c liquibase -n "__fish_seen_subcommand_from drop-all; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'A registered changelog file that identifies the specific Project in which to record your data at Liquibase Hub'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --sql" -a --sql -d 'The SQL string to execute'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --sql-file" -a --sql-file -d 'The SQL file with a script to execute'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --default-catalog-name" -a --default-catalog-name -d 'The default catalog name to use for the database connection'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --default-schema-name" -a --default-schema-name -d 'The default schema name to use for the database connection'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --delimiter" -a --delimiter -d 'The delimiter to use when executing SQL scripts'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --driver" -a --driver -d 'The JDBC driver class'
complete -f -c liquibase -n "__fish_seen_subcommand_from execute-sql; and not __fish_seen_subcommand_from --driver-properties-file" -a --driver-properties-file -d 'The JDBC driver properties file'
complete -f -c liquibase -n "__fish_seen_subcommand_from list-locks; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from list-locks; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from list-locks; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from list-locks; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran-sql; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran-sql; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran-sql; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran-sql; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from mark-next-changeset-ran-sql; and not __fish_seen_subcommand_from --output-file" -a --output-file -d 'Specifies the file path to where the SQL output will be written'
complete -f -c liquibase -n "__fish_seen_subcommand_from release-locks; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from release-locks; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from release-locks; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from release-locks; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag-exists; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag-exists; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag-exists; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from tag-exists; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from unexpected-changesets; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from unexpected-changesets; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from unexpected-changesets; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from unexpected-changesets; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from unexpected-changesets; and not __fish_seen_subcommand_from --verbose" -a --verbose -d 'To see the list of unexpected changesets'
complete -f -c liquibase -n "__fish_seen_subcommand_from validate; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from validate; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from validate; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from validate; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'

# Documentation commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a db-doc -d 'Generates Javadoc-like documentation based on current database and changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from db-doc; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from db-doc; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from db-doc; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from db-doc; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'

# Liquibase Hub commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a register-changelog -d 'Connects your local Liquibase activity to a specific Liquibase Hub Project'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a sync-hub -d 'Synchronizes the local DATABASECHANGELOG table with Liquibase Hub'
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a deactivate-changelog -d 'Removes the changelogID from your changelog file so it stops sending reports to Liquibase Hub'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --hub-api-key" -a --hub-api-key -d 'Specifying the Liquibase Hub API Keys property is required to connect to Liquibase Hub along with a registered changelog file. The API key is unique for each Liquibase Hub user. Liquibase Hub will only be in sync with your actions if the API key is added'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --driver" -a --driver -d 'The JDBC driver class'
complete -f -c liquibase -n "__fish_seen_subcommand_from register-changelog; and not __fish_seen_subcommand_from --hubProjectId" -a --hubProjectId -d 'The JDBC driver class'
complete -f -c liquibase -n "__fish_seen_subcommand_from sync-hub; and not __fish_seen_subcommand_from --hub-connection-id" -a --hub-connection-id -d 'Specifies the target (also called connection) needed for the sync-hub command to synchronize the local DATABASECHANGELOG table with Liquibase Hub'
complete -f -c liquibase -n "__fish_seen_subcommand_from deactivate-changelog; and not __fish_seen_subcommand_from --changelog-file" -a --changelog-file -d 'The root changelog'
complete -f -c liquibase -n "__fish_seen_subcommand_from deactivate-changelog; and not __fish_seen_subcommand_from --url" -a --url -d 'The JDBC database connection URL'
complete -f -c liquibase -n "__fish_seen_subcommand_from deactivate-changelog; and not __fish_seen_subcommand_from --username" -a --username -d 'The database username'
complete -f -c liquibase -n "__fish_seen_subcommand_from deactivate-changelog; and not __fish_seen_subcommand_from --password" -a --password -d 'The database password'

# Quality checks commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a checks -d ''
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from copy" -a copy -d 'The copy subcommand copies a customizable check so that you can run the same check multiple times with different parameters'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from customize" -a customize -d 'The customize subcommand allows you to customize checks specified in your check configurations'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from delete" -a delete -d 'The delete subcommand allows you to delete a copy of a check from your checks settings'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from disable" -a disable -d 'The disable subcommand disables a specific check provided in the --check-name parameter'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from enable" -a enable -d 'The enable subcommand enables a specific check provided in the --check-name parameter'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from reset" -a reset -d 'The reset subcommand reverts customizations made to the check indicated in the --check-name parameter to default settings'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from run" -a run -d 'The run subcommand executes checks using the checks settings file and the changelog file you specify'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from show" -a show -d 'The show subcommand prints the available checks and their configurations as indicated in the check settings file to STDOUT'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and not __fish_seen_subcommand_from $liquibase_checks_commands; and not __fish_seen_subcommand_from bulk-set" -a bulk-set -d '**PRO** The bulk-set command sets all qualifying quality checks to the same value'
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from --check-name" -a --check-name
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and __fish_seen_subcommand_from customize; and not __fish_seen_subcommand_from --check-name" -a --check-name
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and __fish_seen_subcommand_from reset; and not __fish_seen_subcommand_from --check-name" -a --check-name
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from --check-name" -a --check-name
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from --check-name" -a --check-name
complete -f -c liquibase -n "__fish_seen_subcommand_from checks; and __fish_seen_subcommand_from copy; and not __fish_seen_subcommand_from --check-name" -a --check-name

# Other commands
complete -f -c liquibase -n "not __fish_seen_subcommand_from $liquibase_commands" -a --version -d 'Show the curren Liquibase version'
complete -f -c liquibase -n "__fish_seen_subcommand_from $liquibase_commands" -a --log-level -d 'Controls the amount of messages that are generated when running Liquibase commands. The --log-level can be set to the following values: SEVERE (highest level) – Show serious failures that may prevent program execution. WARNING – Show potential problems for program execution. INFO – Show informational messages. FINE (lowest level; formerly DEBUG) – Show tracing information of program execution and minor failures. OFF – Hide all log messages.'
complete -f -c liquibase -n "__fish_seen_subcommand_from $liquibase_commands" -a --log-file -d 'To log execution details of any command, use the log-file parameter. The log-file parameter sends logging messages of what Liquibase does during runtime to a file'